openapi: 3.0.3
info:
  title: Acme Product Catalog API
  version: 0.0.1
paths: {}
components:
  responses:
    406Response:
      description: Not Acceptable
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '../schemas/Error.yaml#/components/schemas/Error'
          example:
            errors:
              - title: Not Acceptable
                status: 406
                detail: >-
                  Accept header contains the JSON:API media type and instances of that
                  media type are modified with media type parameters.
                id: 64ef46ea-30c9-11ed-a261-0242ac120002
