openapi: 3.0.3
info:
  title: Acme Product Catalog API
  version: 0.0.1
paths: {}
components:
  responses:
    415Response:
      description: 415 Unsupported Media Type
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '../schemas/Error.yaml#/components/schemas/Error'
          example:
            errors:
              - title: 415 Unsupported Media Type
                status: 415
                detail: >-
                  Request specifies the header Content-Type: application/vnd.api+json
                  with media type parameters.
                id: ef2692f4-3ca4-44d9-b70a-7cfd5d78d3a1
