/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ErrorErrorsInnerSource
 */
public class ErrorErrorsInnerSourceTest {
    private final ErrorErrorsInnerSource model = new ErrorErrorsInnerSource();

    /**
     * Model tests for ErrorErrorsInnerSource
     */
    @Test
    public void testErrorErrorsInnerSource() {
        // TODO: test ErrorErrorsInnerSource
    }

    /**
     * Test the property 'pointer'
     */
    @Test
    public void pointerTest() {
        // TODO: test pointer
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    public void parameterTest() {
        // TODO: test parameter
    }

}
