/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.model;

import com.acmepetsupplies.model.ProductRelationshipsHasReviews;
import com.acmepetsupplies.model.ProductRelationshipsInCategories;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductRelationships
 */
public class ProductRelationshipsTest {
    private final ProductRelationships model = new ProductRelationships();

    /**
     * Model tests for ProductRelationships
     */
    @Test
    public void testProductRelationships() {
        // TODO: test ProductRelationships
    }

    /**
     * Test the property 'inCategories'
     */
    @Test
    public void inCategoriesTest() {
        // TODO: test inCategories
    }

    /**
     * Test the property 'hasReviews'
     */
    @Test
    public void hasReviewsTest() {
        // TODO: test hasReviews
    }

}
