/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductRelationshipsHasReviewsLinks
 */
public class ProductRelationshipsHasReviewsLinksTest {
    private final ProductRelationshipsHasReviewsLinks model = new ProductRelationshipsHasReviewsLinks();

    /**
     * Model tests for ProductRelationshipsHasReviewsLinks
     */
    @Test
    public void testProductRelationshipsHasReviewsLinks() {
        // TODO: test ProductRelationshipsHasReviewsLinks
    }

    /**
     * Test the property 'related'
     */
    @Test
    public void relatedTest() {
        // TODO: test related
    }

}
