openapi: 3.0.3
info:
  title: Acme Product Catalog API
  version: 0.0.1
paths: {}
components:
  parameters:
    filterCategory:
      name: filterCategory
      required: false
      in: query
      description: Filter by category ID.
      schema:
        type: string
        format: uuid
        maxLength: 40
        example: 1e32231d-b8a1-4145-b539-820301c2af64
