/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.api;

import com.acmepetsupplies.client.ApiException;
import com.acmepetsupplies.model.CategoriesResponse;
import com.acmepetsupplies.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriesApi
 */
@Disabled
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    /**
     * List all categories
     *
     * List all categories.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCategoriesTest() throws ApiException {
        CategoriesResponse response = api.listCategories();
        // TODO: test validations
    }

}
