/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.api;

import com.acmepetsupplies.client.ApiException;
import com.acmepetsupplies.model.Error;
import com.acmepetsupplies.model.ProductsResponse;
import java.util.UUID;
import com.acmepetsupplies.model.ViewProduct200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * List all products
     *
     * List all products.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProductsTest() throws ApiException {
        String include = null;
        UUID filterCategory = null;
        ProductsResponse response = api.listProducts(include, filterCategory);
        // TODO: test validations
    }

    /**
     * View a product&#39;s details
     *
     * View a product&#39;s details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void viewProductTest() throws ApiException {
        UUID id = null;
        ViewProduct200Response response = api.viewProduct(id);
        // TODO: test validations
    }

}
