/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.api;

import com.acmepetsupplies.client.ApiException;
import com.acmepetsupplies.model.Error;
import com.acmepetsupplies.model.ReviewsResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReviewsApi
 */
@Disabled
public class ReviewsApiTest {

    private final ReviewsApi api = new ReviewsApi();

    /**
     * List reviews
     *
     * List all reviews for a product.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProductReviewsTest() throws ApiException {
        UUID id = null;
        ReviewsResponse response = api.listProductReviews(id);
        // TODO: test validations
    }

}
