name: Mainline merge

on:
  push:
    branches:
      - main
env:
  GITHUB_RUN_NUMBER: ${{ github.run_number }}
jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build - Checkout
        uses: actions/checkout@v3
      - name: Build - Start background services
        run: |
          docker compose -f chapter9/compose.yaml up -d
      - name: Install Kusk
        run: |
          curl -sSLf https://raw.githubusercontent.com/kubeshop/kusk-gateway/main/cmd/kusk/scripts/install.sh | bash